spring:
  config:
    activate:
      on-profile: prd
  datasource:
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/superheroes?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl